import {
  AgentNode,
  DecisionSummary,
  FeedEntryItem,
  MemorySummary,
  MissionDetail,
  SystemHealthStatus,
} from '@/types/mission-control';

export const mockSystemStatus: SystemHealthStatus = {
  status: 'ok',
  serviceName: 'Autonomous Intelligence Core',
  timestamp: '2026-08-08T08:00:00.000Z',
  autonomousWorkerActive: true,
  connectionStatus: 'CONNECTED',
};

export const mockCurrentMission: MissionDetail = {
  id: 'mission-8f92a10b',
  title: 'Autonomous Creator Platform Launch',
  objective: 'Execute end-to-end multi-agent pipeline for autonomous asset creation and self-review',
  description: 'Full autonomous mission orchestrating Planner, Research, Decision, Creator, Reviewer, and Reflection engines.',
  status: 'COMPLETED',
  priority: 'high',
  progressPercentage: 100,
  startedAt: '2026-08-08T07:48:00.000Z',
  completedAt: '2026-08-08T08:00:00.000Z',
  currentStage: 'COMPLETED',
  currentAgent: 'System',
};

export const mockAgentNodes: AgentNode[] = [
  {
    id: 'node-mission',
    name: 'Mission Core',
    role: 'Orchestrator',
    description: 'System initialization & lifecycle manager',
    status: 'completed',
    progressPercentage: 100,
    durationMs: 42,
  },
  {
    id: 'node-planner',
    name: 'Planner Agent',
    role: 'Planner',
    description: 'Decomposes objective into milestones & task graph',
    status: 'completed',
    progressPercentage: 100,
    durationMs: 310,
  },
  {
    id: 'node-research',
    name: 'Research Agent',
    role: 'Research',
    description: 'Gathers context & competitive domain evidence',
    status: 'completed',
    progressPercentage: 100,
    durationMs: 480,
  },
  {
    id: 'node-decision',
    name: 'Decision Agent',
    role: 'Decision',
    description: 'Scorers candidate strategies & selects optimal path',
    status: 'completed',
    progressPercentage: 100,
    durationMs: 520,
  },
  {
    id: 'node-creator',
    name: 'Creator Agent',
    role: 'Creator',
    description: 'Synthesizes primary deliverable content artifacts',
    status: 'completed',
    progressPercentage: 100,
    durationMs: 890,
  },
  {
    id: 'node-reviewer',
    name: 'Reviewer Agent',
    role: 'Reviewer',
    description: 'Quality verification & self-correction evaluation',
    status: 'completed',
    progressPercentage: 100,
    durationMs: 410,
  },
  {
    id: 'node-memory',
    name: 'Memory & Reflection',
    role: 'Engine',
    description: 'Post-mission self-review & long-term memory update',
    status: 'completed',
    progressPercentage: 100,
    durationMs: 290,
  },
];

export const mockFeedItems: FeedEntryItem[] = [
  {
    id: 'feed-7',
    mission_id: 'mission-8f92a10b',
    current_stage: 'COMPLETED',
    timestamp: '2026-08-08T08:00:00.000Z',
    agent_responsible: 'System',
    progress_percentage: 100.0,
    summary_of_work: 'Autonomous mission completed successfully.',
    decision_made: 'Completed multi-agent campaign execution',
    confidence: 1.0,
    reflection: 'Performance Score: 0.96 | Lessons Learned: Domain research briefs directly improve decision confidence.',
    event_type: 'MissionCompleted',
  },
  {
    id: 'feed-6',
    mission_id: 'mission-8f92a10b',
    current_stage: 'ReflectionCompleted',
    timestamp: '2026-08-08T07:59:45.000Z',
    agent_responsible: 'ReflectionEngine',
    progress_percentage: 95.0,
    summary_of_work: 'Completed post-mission self-review & memory update.',
    decision_made: 'Persisted lesson learned record',
    confidence: 0.96,
    reflection: 'Zero critical failures detected during pipeline execution.',
    event_type: 'ReflectionCompleted',
  },
  {
    id: 'feed-5',
    mission_id: 'mission-8f92a10b',
    current_stage: 'Review',
    timestamp: '2026-08-08T07:59:15.000Z',
    agent_responsible: 'ReviewerAgent',
    progress_percentage: 90.0,
    summary_of_work: 'Evaluated deliverable quality against domain criteria (Score: 0.95).',
    decision_made: 'Approved deliverable quality',
    confidence: 0.95,
    event_type: 'ReviewerCompleted',
  },
  {
    id: 'feed-4',
    mission_id: 'mission-8f92a10b',
    current_stage: 'Creation',
    timestamp: '2026-08-08T07:58:30.000Z',
    agent_responsible: 'CreatorAgent',
    progress_percentage: 75.0,
    summary_of_work: "Synthesized primary deliverable artifact: 'Autonomous Output: Platform Launch'",
    decision_made: 'Drafted asset outputs for quality review',
    confidence: 0.95,
    event_type: 'CreatorCompleted',
  },
  {
    id: 'feed-3',
    mission_id: 'mission-8f92a10b',
    current_stage: 'Decision',
    timestamp: '2026-08-08T07:57:30.000Z',
    agent_responsible: 'DecisionAgent',
    progress_percentage: 55.0,
    summary_of_work: 'Evaluated 2 candidate strategies using risk-weighted impact scores.',
    decision_made: "Selected 'Strategy A: Deep Comprehensive Execution'",
    confidence: 0.94,
    event_type: 'DecisionCompleted',
  },
  {
    id: 'feed-2',
    mission_id: 'mission-8f92a10b',
    current_stage: 'Researching',
    timestamp: '2026-08-08T07:56:20.000Z',
    agent_responsible: 'ResearchAgent',
    progress_percentage: 35.0,
    summary_of_work: 'Compiled domain evidence brief & validated compliance requirements.',
    decision_made: 'Validated evidence alignment for strategy evaluation',
    confidence: 0.95,
    event_type: 'ResearchCompleted',
  },
  {
    id: 'feed-1',
    mission_id: 'mission-8f92a10b',
    current_stage: 'Planning',
    timestamp: '2026-08-08T07:55:00.000Z',
    agent_responsible: 'PlannerAgent',
    progress_percentage: 15.0,
    summary_of_work: 'Decomposed objective into 2 milestones, 2 tasks, and 2 candidate strategies.',
    decision_made: 'Structured mission milestone roadmap',
    confidence: 0.95,
    event_type: 'PlannerCompleted',
  },
];

export const mockDecisionSummary: DecisionSummary = {
  missionId: 'mission-8f92a10b',
  selectedStrategyTitle: 'Strategy A: Deep Comprehensive Execution',
  reasoning: 'Goal analysis confirmed objective requirements. Selected Strategy A with top composite score of 0.94 based on domain evidence and risk-weighted impact.',
  confidenceScore: 0.94,
  evaluationsCount: 2,
  options: [
    {
      id: 'opt-agile',
      title: 'Strategy B: Fast Agile Execution',
      score: 0.85,
      status: 'REJECTED',
      description: 'Focus on high-speed synthesis and rapid prototyping of outputs.',
      rationale: 'High efficiency, but lower composite elaboration depth.',
    },
    {
      id: 'opt-comprehensive',
      title: 'Strategy A: Deep Comprehensive Execution',
      score: 0.94,
      status: 'SELECTED',
      description: 'Focus on extensive multi-angle contextual analysis and exhaustive elaboration.',
      rationale: 'Maximum depth and highest quality verification score.',
    },
  ],
};

export const mockMemorySummary: MemorySummary = {
  totalRecords: 14,
  insightsCount: 9,
  reflectionsCount: 5,
  recentLessons: [
    {
      id: 'mem-1',
      summary: 'Domain research briefs directly improve decision confidence (level: 0.94).',
      insight: 'Including key compliance insights in research briefs reduces revision loops during review phase.',
      confidenceScore: 0.96,
      createdAt: '2026-08-08T07:45:00.000Z',
    },
    {
      id: 'mem-2',
      summary: 'Strategy A provides optimal quality for multi-agent deliverables.',
      insight: 'Composite scoring favors comprehensive multi-angle strategy over rapid agile prototyping.',
      confidenceScore: 0.95,
      createdAt: '2026-08-08T06:00:00.000Z',
    },
  ],
};
